apiVersion: v1

kind: Service

metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-app-usingpods

spec:
  type: LoadBalancer

  ports:
  - targetPort: 80
    port: 80

  selector:
    name: result-app-pod
    app: voting-app-usingpods

